spring:
  #  profiles:
  #    active: local
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 5000
    password:
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        min-idle: 0
        max-idle: 20
  application:
    name: my-sample
  security:
    user:
      password: none
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      percentage: 1
  cloud:
    services:
      registrationMethod: route
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源，替换C3P0
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connection-timeout: 50000
      maximum-pool-size: 500
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 50000
    tomcat:
      max-idle: 2
      min-idle: 2
      initial-size: 2

server:
  port: 8001
  servlet:
    context-path: /sample

log4j2:
  logging:
    config: classpath:log4j2.yml
    level:
      root: INFO

lc:
  config:
    # 登录相关配置
    login:
      loginErrorCount: 5
      errorExpMinutes: 5
      captchaKey: code
      errorKey: err_
      stopLoginKey: stop_
    # 雪花算法 id生成规则相关
    idWork:
      # 自定义数据中心标识 设置小于5位
      datacenterId: 1
      # 自定义机器标识 设置小于5位
      machineId: 1




